// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKj0JRvVnWw21XSONc6CarV6EiY4p1P14',
    appId: '1:805274963759:web:e11e9b2347dcf83c24dbda',
    messagingSenderId: '805274963759',
    projectId: 'odes-59f3e',
    authDomain: 'odes-59f3e.firebaseapp.com',
    storageBucket: 'odes-59f3e.firebasestorage.app',
    measurementId: 'G-E8L22WC9BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8tpmOxLxoRYX2dvqizMP26t53YqMQrf8',
    appId: '1:805274963759:android:36b2aa045d7e084f24dbda',
    messagingSenderId: '805274963759',
    projectId: 'odes-59f3e',
    storageBucket: 'odes-59f3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCr5739RwCnM_1-2h8981RjrnDITpK_oQ',
    appId: '1:805274963759:ios:f1e500c2f4523b9424dbda',
    messagingSenderId: '805274963759',
    projectId: 'odes-59f3e',
    storageBucket: 'odes-59f3e.firebasestorage.app',
    iosBundleId: 'com.example.todoWithNodejs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCr5739RwCnM_1-2h8981RjrnDITpK_oQ',
    appId: '1:805274963759:ios:f1e500c2f4523b9424dbda',
    messagingSenderId: '805274963759',
    projectId: 'odes-59f3e',
    storageBucket: 'odes-59f3e.firebasestorage.app',
    iosBundleId: 'com.example.todoWithNodejs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKj0JRvVnWw21XSONc6CarV6EiY4p1P14',
    appId: '1:805274963759:web:4ab862930a60246b24dbda',
    messagingSenderId: '805274963759',
    projectId: 'odes-59f3e',
    authDomain: 'odes-59f3e.firebaseapp.com',
    storageBucket: 'odes-59f3e.firebasestorage.app',
    measurementId: 'G-K25JY9YGK5',
  );
}
